name: reverbio
description: Music Streaming app made in Flutter!
homepage: https://github.com/akashskypatel/Reverbio
repository: https://github.com/akashskypatel/Reverbio
issue_tracker: https://github.com/akashskypatel/Reverbio/issues

publish_to: 'none'
version: 1.4.0 # run update.sh after changing the version

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ^3.29.0

dependencies:
  app_links: ^6.4.0
  audio_service: ^0.18.17
  audio_session: ^0.2.2
  cached_network_image: ^3.4.1
  csv: ^6.0.0
  discogs_api_client: ^0.1.6
  dynamic_color: ^1.7.0
  file_picker: ^10.1.2
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.6
  flutter_js: ^0.8.5
  flutter_localizations:
    sdk: flutter
  fuzzy: ^0.5.1
  fuzzywuzzy: ^1.2.0
  go_router: ^15.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.5
  http: ^1.3.0
  intl: 0.20.2
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  musicbrainz_api_client: ^0.1.8
  path: ^1.9.1
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  youtube_explode_dart: ^2.4.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5

  # flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/licenses/
    - assets/images/
    - .env

  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf
    - family: montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-VariableFont_wght.ttf
        - asset: fonts/montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic

flutter_native_splash:
  color: '#f9fafd'
  image: assets/images/ic_splash.png
  color_dark: '#151515'
  image_dark: assets/images/ic_splash.png

  android_12:
    image: assets/images/ic_splash.png
    image_dark: assets/images/ic_splash.png

flutter_launcher_icons:
  android: true
  adaptive_icon_background: '#191919'
  adaptive_icon_foreground: 'assets/images/ic_launcher_foreground.png'
  adaptive_icon_round: 'assets/images/ic_launcher_round.png'
  adaptive_icon_monochrome: 'assets/images/ic_launcher_monochrome.png'
  android_notification_icon : 'assets/images/ic_notification.png'
  image_path: 'assets/images/ic_launcher.png'
  windows:
    generate: true
    image_path: "assets/images/ic_splash.png"
    icon_size: 256 # min:48, max:256, default: 48

flutter_lints: ^5.0.0