name: Release Testing Tasklist
description: Testing checklist before new release
title: '[Release] vX.X.X <platform> Testing Checklist'
labels: ["release"]
assignees:
  - akashskypatel

body:
  - type: checkboxes
    id: application
    attributes:
      label: Application
      description: Make sure the application launches without errors.
      options:
        - label: Make sure the application launches without errors.
          required: false
        - label: Verify cache data is created inn application diirectory.
          required: false
