name: Release Testing Tasklist
description: Testing checklist before new release
title: '[Release] vX.X.X <platform> Testing Checklist'
labels: ["release"]
assignees:
  - akashskypatel

body:
  - type: checkboxes
    id: application
    attributes:
      label: Application
      description: Make sure the application launches without errors.
      options:
        - label: Make sure the application launches without errors.
          required: false
        - label: Verify cache data is created inn application diirectory.
          required: false

  - type: checkboxes
    id: homepage
    attributes:
      label: Home page
      description: Complete or verify all features on Home Page.
      options:
        - label: Suggested Playlists loads with Image and Labels successfully.
          required: false
        - label: Suggested Artists loads with Image and Labels successfully.
          required: false
        - label: Recommended for you loads with Image and Labels successfully.
          required: false
        - label: Refresh Home Page completes successfully.
          required: false
        - label: Liking artist, playlist, and song completes successfully.
          required: false
        - label: Recommended for you toolbox opens and closes successfully.
          required: false
        - label: Recommended for you songs can be played successfully (if stream found).
          required: false
        - label: If song stream found, can be opened in youtube successfully.
          required: false
        - label: Recommended for you songs can be queued, played, shuffled, and sorted successfully.
          required: false
        - label: A Recommended for you Song can be liked, added to playlist, added to queue, and added to offline successfully.
          required: false
        - label: A Recommended for you Song can be disliked, removed from playlist, removed from queue, and removed from offline successfully.
          required: false
        - label: Double tapping a song likes/dislikes a song.
          required: false
