name: Release Testing Tasklist
description: Testing checklist before new release
title: '[Release] vX.X.X <platform> Testing Checklist'
labels: ["release"]
assignees:
  - akashskypatel

body:
  - type: checkboxes
    id: application
    attributes:
      label: Application
      description: Make sure the application launches without errors.
      options:
        - label: Make sure the application launches without errors.
          required: false
        - label: Verify cache data is created inn application directory.
          required: false

  - type: checkboxes
    id: homepage
    attributes:
      label: Home page
      description: Complete or verify all features on Home Page.
      options:
        - label: Suggested Playlists loads with Image and Labels successfully.
          required: false
        - label: Suggested Artists loads with Image and Labels successfully.
          required: false
        - label: Recommended for you loads with Image and Labels successfully.
          required: false
        - label: Refresh Home Page completes successfully.
          required: false
        - label: Liking artist, playlist, and song completes successfully.
          required: false
        - label: Recommended for you toolbox opens and closes successfully.
          required: false
        - label: Recommended for you songs can be played successfully (if stream found).
          required: false
        - label: If song stream found, can be opened in youtube successfully.
          required: false
        - label: Recommended for you songs can be queued, played, shuffled, and sorted successfully.
          required: false
        - label: A Recommended for you Song can be liked, added to playlist, added to queue, and added to offline successfully.
          required: false
        - label: A Recommended for you Song can be disliked, removed from playlist, removed from queue, and removed from offline successfully.
          required: false
        - label: Double tapping a song likes/dislikes a song.
          required: false

  - type: checkboxes
    id: searchpage
    attributes:
      label: Search page
      description: Complete or verify all features on Search Page.
      options:
        - label: Suggested Playlists loads with Image and Labels successfully.
          required: false
        - label: Typing in search bar is successful and shows suggestions successfully.
          required: false
        - label: Submitting search query shows search results successfully.
          required: false
        - label: Clicking on search suggestions shows search results successfully.
          required: false
        - label: Search result pages can successfully be iterated up and down for all search entities.
          required: false
        - label: Search result entities can be liked/disliked successfully.
          required: false
        - label: Search result songs can be played successfully (if stream found).
          required: false
        - label: If song stream found, can be opened in youtube successfully.
          required: false
        - label: Song results can be queued, played, shuffled, and sorted successfully.
          required: false
        - label: A Song result can be liked, added to playlist, added to queue, and added to offline successfully.
          required: false
        - label: A Song result can be disliked, removed from playlist, removed from queue, and removed from offline successfully.
          required: false
        - label: Double tapping a song likes/dislikes a song.
          required: false

  - type: checkboxes
    id: librarypage
    attributes:
      label: Library page
      description: Complete or verify all features on Library Page.
      options:
        - label: Add a custom playlist using YouTube link.
          required: false
        - label: Add a local custom playlist.
          required: false
        - label: Confirm liked playlist from home page shows under liked playlists.
          required: false
        - label: Search for playlist in library and clear searched filter.
          required: false
        - label: Remove liked playlist.
          required: false
        - label: Remove added playlist.
          required: false
        - label: Remove local playlist.
          required: false
        - label: Navigate to each library page- Recently Played, Liked Songs, Liked Artists, Liked Albums, and Offline Songs.
          required: false

  - type: checkboxes
    id: recentlyplayed
    attributes:
      label: Recently Played page
      description: Complete or verify all features on Recently Played Page.
      options:
        - label: Confirm recently played songs show in the list
          required: false
