/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ReverbioIcons {
  ReverbioIcons._();

  static const _kFontFam = 'ReverbioIcons';
  static const String? _kFontPkg = null;

  static const IconData android_auto_monochrome = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
